### ISSUE TITLE
Data Leak on Server

### ISSUE THREAD

**Issue by Orihkeks** [Georgi-Kalkovski/GW2Geary#2]
Issue:
Dataleak from E-Mail Address, User_Ids, API-Keys and other User only Data in Production
Also Deleting of Accounts, changing passwords and more is possible.

Where:
[auth.controller](https://github.com/Georgi-Kalkovski/GW2Geary/blob/main/server/controllers/auth.controller.js)
[auth.routes](https://github.com/Georgi-Kalkovski/GW2Geary/blob/main/server/routes/auth.routes.js)

All routes are not protected by the middleware and the userid is extractable over
-> api/auth/getUser?name=
should be fixed ASAP.

**Comment by Georgi-Kalkovski** [comment]
Dataleak has been fixed. Now a jwt token is required.

**Comment by Orihkeks** [comment]
Applying Snake Oil to it, does not fix it.

Your jwst token does not check for the user rights, it just checks for existence.
What just make it useless.

**Comment by Georgi-Kalkovski** [comment]
> Applying Snake Oil to it, does not fix it.
> 
> Your jwst token does not check for the user rights, it just checks for existence. What just make it useless.

Thanks for the heads-up. It should be fixed now.
